version: '2'
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "8082:80/tcp"
    volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins
    # extra_hosts:
    # - "jenkins:172.24.0.5"
  jenkins:
    container_name: jenkins
    image: jenkins:2.46.3
    entrypoint: ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
    ports:
      - "8080:8080/tcp"
  jenkins2:
    container_name: jenkins2
    image: jenkins:2.46.3
    entrypoint: ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
